apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - namespaces.yaml
  - kubevirt-operator.yaml
  - kubevirt-cr.yaml
  - cdi-operator.yaml
  - cdi-cr.yaml
  - cdi-storage-profile.yaml
  - ubuntu-legacy-web.yaml
  - container-demo.yaml
